version: '2'
services:
  mysql:
    container_name: local_db
    restart: always
    image: mysql:latest
    ports:
        - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'test'
      MYSQL_PASS: 'password'
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume: